pipeline {
    agent {
        label 'agent-1'
    } 

    environment {
        appVersion = ""
        REGION = "us-east-1"
        ACC_ID = "838180513114"
        PROJECT = "roboshop"
        COMPONENT = "catalogue"
    }

    options {
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    stages {

        stage('Verify AWS Identity') {
            steps {
                script {
                    withAWS(credentials: 'aws-cerds', region: "${REGION}") {
                        sh '''
                            echo "=== WHO AM I (Jenkins) ==="
                            aws sts get-caller-identity

                            echo "=== REGION ==="
                            aws configure get region || echo "No region configured"
                        '''
                    }
                }
            }
        }

        stage('Init') {
            steps {
                withAWS(credentials: 'aws-cerds', region: "${REGION}") {
                    dir('60-acm') {
                        sh 'terraform init -reconfigure'
                    }
                }
            }
        }

        stage('terraform plan') {
            steps {
                withAWS(credentials: 'aws-cerds', region: "${REGION}") {
                    dir('60-acm') {
                        sh 'terraform plan'
                    }
                }
            }
        }

        stage('terraform apply') {
            steps {
                withAWS(credentials: 'aws-cerds', region: "${REGION}") {
                    dir('60-acm') {
                        sh 'terraform apply -auto-approve'
                    }
                }
            }
        }

    } 

    post { 
        always { 
            echo 'I will always say Hello again!'
        }
        success { 
            echo 'Pipeline success'
        }
        failure { 
            echo 'Pipeline failed'
        }
    }

}