pipeline {
    agent {
        label 'agent-1'
    } 
    environment {
        appVersion = ""
        REGION = "us-east-1"
        ACC_ID = "838180513114"
        PROJECT = "roboshop"
        COMPONENT = "catalogue"
    }
    options {
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    stages {
    stage('Verify AWS Identity') {
        steps {
            script {
                withAWS(credentials: 'aws-cerds', region: "${REGION}") {
                    sh '''
                        echo "=== WHO AM I (Jenkins) ==="
                        aws sts get-caller-identity

                        echo "=== REGION ==="
                        aws configure get region || echo "No region configured"

                        echo "=== VPCs visible ==="
                        aws ec2 describe-vpcs --query "Vpcs[*].VpcId"
                    '''
                }
            }
        }
    }
    stage('Init') {
        steps {
            script {
                withAWS(credentials: 'aws-cerds', region: "${REGION}") {
                    sh """
                        cd 00-vpc
                        terraform init -reconfigure
                    """
                }
            }
        }
    }
    stage('terraform plan') {
        steps {
            script {
                withAWS(credentials: 'aws-cerds', region: "${REGION}") {
                    sh """
                        cd 00-vpc
                        terraform plan
                    """
                }
            }
        }
    }
    stage('terraform apply') {
        input {
            message "Should we continue?"
            ok "Yes, we should."
            submitter "alice,bob"
        }
        steps {
            script {
                withAWS(credentials: 'aws-cerds', region: "${REGION}") {
                    sh """
                        cd 00-vpc
                        terraform apply -auto-approve
                    """
                }
            }
        }
    }


    post { 
        always { 
            echo 'I will always say Hello again!'
        }

        success { 
            echo 'If success say ..I will always say Hello again!'
        }

        
        failure { 
            echo 'If failure say ..I will always say stage is failure!'
        }
    }

 }
 }