pipeline {
    agent {
        label 'agent-1'
    } 

    environment {
        appVersion = ""
        REGION = "us-east-1"
        ACC_ID = "838180513114"
        PROJECT = "roboshop"
        COMPONENT = "catalogue"
    }

    options {
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    stages {

        stage('Verify AWS Identity') {
            steps {
                script {
                    withAWS(credentials: 'aws-cerds', region: "${REGION}") {
                        sh '''
                            echo "=== WHO AM I (Jenkins) ==="
                            aws sts get-caller-identity

                            echo "=== REGION ==="
                            aws configure get region || echo "No region configured"
                        '''
                    }
                }
            }
        }

        stage('Init') {
            steps {
                withAWS(credentials: 'aws-cerds', region: "${REGION}") {
                    dir('10-sg') {
                        sh 'terraform init -reconfigure'
                    }
                }
            }
        }

        stage('terraform plan') {
            steps {
                withAWS(credentials: 'aws-cerds', region: "${REGION}") {
                    dir('10-sg') {
                        sh 'terraform plan'
                    }
                }
            }
        }

        stage('terraform apply') {
            steps {
                withAWS(credentials: 'aws-cerds', region: "${REGION}") {
                    dir('10-sg') {
                        sh 'terraform apply -auto-approve'
                    }
                }
            }
        }

        stage('BASTION ACM EKS') {
            parallel {
                stage('Trigger BASTION') {
                    steps {
                        build job: '20-bastion',
                        wait: false, // VPC will not wait for SG pipeline completion
                        propagate: false // even SG fails VPC will not be effected
                    }
                }
                stage('Trigger ACM') {
                    steps {
                        build job: '60-acm',
                        wait: false,
                        propagate: false
                    }
                }
                stage('Trigger EKS') {
                    steps {
                        build job: '80-eks',
                        wait: false,
                        propagate: false
                    }
                }
            }
        }
        stage('Trigger alb') {
            steps {
                script {
                    build job: '70-ingress-alb',
                    wait: false,
                    propagate: false
                }
            }
        }
    }

    post { 
        always { 
            echo 'I will always say Hello again!'
        }
        success { 
            echo 'Pipeline success'
        }
        failure { 
            echo 'Pipeline failed'
        }
    }

}